FROM python:latest as list_products
LABEL Maintainer="polina.sysolyatina"
WORKDIR /usr/app/src

COPY shopping_cart.py ./

COPY requirements.txt ./

RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED 1
COPY . .

CMD ["python", "shopping_cart.py"]
